### PR TITLE
Feature conan

### PR DESCRIPTION
**Pull request by vgonisanz**
Refactor source structure and compile files to support conan instead manually manage dependencies and distribution

### CODE REVIEW

**Comment by vgonisanz** [comment]
@ntamurejocolorado this is ready to review. @IslameN  you may want to test on MacOS

**Comment by IslameN** [comment]
It is not working on my PC (Ubuntu 20.04.2 LTS). Attached file.

[env-create.txt](https://github.com/vgonisanz/nci/files/6213700/env-create.txt)

**Comment by IslameN** [comment]
It was a problem with previous build folder.

Now it compiles well and run tests. However `make run`  failts:
```
Error opening terminal: xterm-256color.
make: *** [Makefile:62: run] Error 1
```
The samples in `bin` folder say the same error.

**Comment by vgonisanz** [comment]
Please, before proceed with the merge review this issue: https://github.com/vgonisanz/nci/issues/9

**Review by ntamurejocolorado — APPROVED** [review]

**Pull request merged**
